In [1]:
import pandas as pd
import numpy as np
from src import format
import string

In [2]:
clubs = format.clean_data()

In [3]:
clubs.sample(10)

Club Status    Ship City Ship State Code Ship Zip  \
495       Active       Orinda              CA    94563   
1600   Cancelled       Dundee              MI    48131   
1667      OnHold  Simi Valley              CA    93065   
2242   Cancelled         Napa              CA    94559   
2417   Cancelled    Calistoga              CA    94515   
1595      Active       Aurora              CO    80013   
32     Cancelled      Laplace              LA    70068   
3816      Active      Wayzata              MN    55391   
4017   Cancelled     new york              NY    10013   
92     Cancelled    Calistoga              CA    94515   

                  Cancel Reason Last Processed Date Last Order Date_x  \
495                         NaN              2/4/19            2/4/19   
1600  Cutting Expenses/Lost Job              4/2/18           6/15/18   
1667                        NaN              2/4/19            2/4/19   
2242  Cutting Expenses/Lost Job              7/9/18            7/9/18   
2417                      Other            11/27/17           3/24/19   
1595                        NaN              2/4/19           2/28/19   
32          Switched Club Level              2/1/16            2/4/19   
3816                        NaN              2/4/19            2/4/19   
4017  Cutting Expenses/Lost Job              2/4/19            2/4/19   
92                          NaN                 NaN               NaN   

                     Club  Customer Number  \
495              3-Bottle            12245   
1600             3-Bottle            19648   
1667             3-Bottle            19939   
2242  3-Bottle (Industry)            22608   
2417             3-Bottle            23222   
1595             3-Bottle            19627   
32               6-Bottle             7342   
3816             3-Bottle            34109   
4017             6-Bottle            34817   
92               6-Bottle             8106   

      Shipments (note that these don't necessarily mean orders)  ...  \
495                                                   8          ...   
1600                                                  5          ...   
1667                                                  9          ...   
2242                                                  2          ...   
2417                                                  1          ...   
1595                                                  8          ...   
32                                                    5          ...   
3816                                                  2          ...   
4017                                                  1          ...   
92                                                    0          ...   

             age  isPickup  clubLength  Customer No.  Number Of Transactions  \
495    36.000000     False    2.583333         12245                    13.0   
1600   41.000000     False    1.333333         19648                    10.0   
1667  114.000000     False    2.000000         19939                    12.0   
2242   31.000000      True    0.666667         22608                    14.0   
2417   30.000000      True    1.333333         23222                    24.0   
1595   40.000000     False    2.666667         19627                    26.0   
32     68.000000     False    4.583333          7342                    13.0   
3816   54.000000     False    1.416667         34109                     5.0   
4017   42.000000     False    1.250000         34817                     4.0   
92     49.745787     False    0.000000          8106                     0.0   

      Lifetime Value_y  Last Order Date_y Last Order Amount Quantity    Total  
495         $1,814.64              2/4/19          $172.44      51.0  1476.25  
1600        $1,545.00             6/15/18          $162.18       NaN      NaN  
1667        $1,559.39              2/4/19          $172.44       NaN      NaN  
2242        $1,273.74              7/9/18          $108.86   

In [7]:
clubs.columns

Index(['Club Status', 'Bill Birth Date', 'Ship Birth Date', 'Ship City',
       'Ship State Code', 'Ship Zip', 'Pickup Location', 'Cancel Date',
       'Cancel Reason', 'Last Processed Date', 'Last Order Date_x', 'Club',
       'Customer Number', 'Signup Date',
       'Shipments (note that these don't necessarily mean orders)',
       'Lifetime Value_x', 'ltv', 'age', 'isPickup', 'cancel', 'signup',
       'clubLength', 'Customer No.', 'Number Of Transactions',
       'Lifetime Value_y', 'Last Order Date_y', 'Last Order Amount',
       'Quantity', 'Total'],
      dtype='object')

In [6]:
clubs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4366 entries, 0 to 4365
Data columns (total 29 columns):
Club Status                                                  4365 non-null object
Bill Birth Date                                              4366 non-null object
Ship Birth Date                                              4035 non-null object
Ship City                                                    4366 non-null object
Ship State Code                                              4366 non-null object
Ship Zip                                                     4366 non-null object
Pickup Location                                              1213 non-null object
Cancel Date                                                  2071 non-null object
Cancel Reason                                                1826 non-null object
Last Processed Date                                          3827 non-null object
Last Order Date_x                                            4344 non-nul

In [2]:
path = '../club_members.csv'
clubs = pd.read_csv(path)

In [3]:
clubs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4366 entries, 0 to 4365
Data columns (total 19 columns):
Club                                                         4366 non-null object
Club Status                                                  4358 non-null object
Customer Number                                              4366 non-null int64
Bill Birth Date                                              4026 non-null object
Bill City                                                    4361 non-null object
Bill State Code                                              4361 non-null object
Bill Zip                                                     4358 non-null object
Ship Birth Date                                              3986 non-null object
Ship City                                                    4360 non-null object
Ship State Code                                              4360 non-null object
Ship Zip                                                     4357 non-null

**These have full values**
```
Club                                                         4366 non-null object
Customer Number                                              4366 non-null int64
Signup Date                                                  4366 non-null object
Shipments (note that these don't necessarily mean orders)    4366 non-null int64
Lifetime Value                                               4366 non-null object
```

**Need to fill NaNs for**
```
Club Status (Done)                                                4358 non-null object
Bill Birth Date  (Done ---> "age")                                           4026 non-null object
Ship City     (Calistoga)                                               4360 non-null object
Ship State Code   (CA)                                           4360 non-null object
Ship Zip          (94515)                                          4357 non-null object
Pickup Location    (Done ---> "isPickup")                                          1213 non-null object
Cancel Date        (Done ---> "clubLength")                                          2071 non-null object
Cancel Reason      (Keep NaNs?)                                         1826 non-null object
Last Processed Date                                         3827 non-null object
Last Order Date                                              4344 non-null object
```

**Don't need**
```
Bill City                                                    4361 non-null object
Bill State Code                                              4361 non-null object
Bill Zip                                                     4358 non-null object
```

**CLEAN UP Clubs**

In [4]:
nans = ["Club Status","Bill Birth Date","Ship Birth Date","Ship City","Ship State Code","Ship Zip","Pickup Location","Cancel Date","Cancel Reason","Last Processed Date","Last Order Date"]
delete = ["Bill City","Bill State Code","Bill Zip"]
keep = ["Club","Customer Number","Signup Date","Shipments (note that these don't necessarily mean orders)","Lifetime Value"]


In [5]:
clubs = clubs[nans + keep]

In [6]:
clubs["ltv"] = [float( "".join((ltv[1:].split(","))) ) for ltv in clubs["Lifetime Value"]]

In [7]:
clubs.loc[clubs["Club Status"].isna() & clubs["Cancel Date"].isna(),"Club Status"] = "Active"

In [8]:
clubs.loc[clubs["Club Status"].isna() & ~clubs["Cancel Reason"].isna(),"Club Status"] = "Cancelled"

In [9]:
clubs.loc[ (clubs["Bill Birth Date"].isna() & ~clubs["Ship Birth Date"].isna()) , "Bill Birth Date"] = clubs["Ship Birth Date"]

In [10]:
clubs.loc[ (~clubs["Bill Birth Date"].isna() & clubs["Ship Birth Date"].isna()) , "Ship Birth Date"] = clubs["Bill Birth Date"]


In [11]:
clubs.loc[ (clubs["Bill Birth Date"].isna() ),"Bill Birth Date" ] = str(1/1/20)

In [12]:
clubs["age"] = np.array( [(2019-int("19" + "".join(bd[-2::]))) for bd in clubs[~clubs["Bill Birth Date"].isna()]
                        ["Bill Birth Date"] ])

In [13]:
clubs.loc[(clubs["age"]==99),"age"] = clubs.loc[~(clubs["age"]==99),"age"].values.mean()

In [14]:
clubs.loc[clubs["Ship City"].isna(),"Ship City"] = "Calistoga"
clubs.loc[clubs["Ship State Code"].isna(),"Ship State Code"] = "CA"
clubs.loc[clubs["Ship Zip"].isna(),"Ship Zip"] = "94515"

In [15]:
clubs["isPickup"] = ~clubs["Pickup Location"].isna()

In [16]:
clubs["cancel"] = np.array([str(cancel).split("/")[0::2] for cancel in clubs["Cancel Date"]])

In [43]:
clubs["signup"] = [list(str(signup).split("/")[0::2]) for signup in clubs["Signup Date"]]

In [41]:
clubs["clubLength"] = [(int(end[1]) - int(start[1])) +  ((( (int(end[0])+12) - int(start[0]) ) % 12  ) / 12 ) if (len(end)==2) else (19 - int(start[1])) +  ((( (3+12) - int(start[0]) ) % 12  ) / 12 ) for end,start in zip(clubs["cancel"],clubs["signup"]) ]


In [42]:
clubs.sample(15)

Club Status Bill Birth Date Ship Birth Date        Ship City  \
3616   Cancelled          6/1/72          6/1/72  El Dorado Hills   
2308      Active         3/30/64         3/30/64         Cheyenne   
2488   Cancelled         9/22/81         9/22/81     Redwood City   
4129      Active         6/25/89         6/25/89    san francisco   
2993   Cancelled        11/13/85        11/13/85    Overland Park   
1132   Cancelled          9/7/75          9/7/75          modesto   
2433   Cancelled        10/29/76        10/29/76    San Francisco   
2457   Cancelled          4/8/52          4/8/52         Estacada   
2945   Cancelled        11/30/87        11/30/87    San Francisco   
3656   Cancelled         3/15/83         3/15/83        arlington   
370    Cancelled          5/4/76          5/4/76       Greenville   
1668      Active         5/11/68         5/11/68   Winter Springs   
1515      Active          2/3/78          2/3/78      Mill Valley   
3272      Active          3/8/90          3/8/90    Castro Valley   
1823   Cancelled         6/21/85         6/21/85      Tahoe vista   

     Ship State Code Ship Zip     Pickup Location Cancel Date  \
3616              CA    95762  Tank Garage Winery      3/9/19   
2308              WY    82009                 NaN         NaN   
2488              CA    94063                 NaN      3/6/19   
4129              CA    94118  Tank Garage Winery         NaN   
2993              KS    66211                 NaN    12/21/18   
1132              CA    95356  Tank Garage Winery     9/17/18   
2433              CA    94111  Tank Garage Winery     7/10/18   
2457              OR    97023                 NaN      2/5/18   
2945              CA    94117  Tank Garage Winery    11/30/18   
3656              VA    22206                 NaN    12/10/18   
370               SC    29607                 NaN      2/3/16   
1668              FL    32708                 NaN         NaN   
1515              CA    94941  Tank Garage Winery         NaN   
3272              CA    94546  Tank Garage Winery         NaN   
1823              CA    96148                 NaN     8/14/18   

                     Cancel Reason Last Processed Date  ... Customer Number  \
3616           Switched Club Level              2/4/19  ...           33264   
2308                           NaN              2/4/19  ...           22809   
2488     Cutting Expenses/Lost Job              2/4/19  ...           23431   
4129                           NaN                 NaN  ...           35804   
2993     Cutting Expenses/Lost Job             12/3/18  ...           25816   
1132                           NaN                 NaN  ...           16881   
2433  Suspend Until Further Notice              7/9/18  ...           23276   
2457     Cutting Expenses/Lost Job              2/5/18  ...           23346   
2945     Cutting Expenses/Lost Job                 NaN  ...           25654   
3656                           NaN             12/3/18  ...           33439   
370                  Too Much Wine             9/28/15  ...           11027   
1668                           NaN              2/5/19  ...           19940   
1515                           NaN              2/5/19  ...           19198   
3272                           NaN             12/3/18  ...           28238   
1823               No Reason Given              7/9/18  ...           20888   

     Signup Date  Shipments (note that these don't necessarily mean orders)  \
3616     9/10/18                                                  3           
2308     9/23/17                                                  8           
2488    11/17/17                                                  7           
4129     1/19/19                                                  0           
2993     4/14/18                                                  3           
1132     7/22/18                                                  0           
2433     11/4/17                         

**Drop**
```
Ship Birth Date
```
**Make index**
```
Customer Number
```


In [45]:
path = '../customer_list.csv'
customers = pd.read_csv(path)

In [46]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32820 entries, 0 to 32819
Data columns (total 10 columns):
Customer No.              32820 non-null int64
City                      10620 non-null object
State                     10658 non-null object
Zip Code                  10923 non-null object
Number Of Transactions    32817 non-null float64
Lifetime Value            32820 non-null object
Last Order Date           20185 non-null object
Last Order Amount         32820 non-null object
Date Added                32820 non-null object
Last Modified Date        32820 non-null object
dtypes: float64(1), int64(1), object(8)
memory usage: 2.5+ MB


**Combine Customers (POS data?) onto Club**

In [52]:
# customers["ltv"] = [float("".join((ltv[1:].split(","))) ) for ltv in customers["Lifetime Value"]]
clubs = clubs.merge(customers[['Customer No.','Number Of Transactions','Lifetime Value','Last Order Date','Last Order Amount']],how="left",left_on="Customer Number",right_on="Customer No.")
clubs.sample(10)

Club Status Bill Birth Date Ship Birth Date      Ship City  \
2668      Active          9/3/66          9/3/66     Cincinnati   
2989   Cancelled         3/14/85         3/14/85    Los Angeles   
1325   Cancelled         11/5/93         11/5/93           Napa   
3578      Active         9/29/85         9/29/85        Atlanta   
4066   Cancelled        10/22/82        10/22/82      Daly City   
2504      Active         10/9/60         10/9/60   san clemente   
1577   Cancelled        11/22/74        11/22/74  San Francisco   
2276      Active         2/19/90          1/1/00           Kent   
1943   Cancelled          8/1/61          8/1/61     San Rafael   
4055      Active         3/10/75         3/10/75       kirkland   

     Ship State Code Ship Zip     Pickup Location Cancel Date  \
2668              OH    45244                 NaN         NaN   
2989              CA    90015                 NaN     11/7/18   
1325              CA    94558  Tank Garage Winery     4/30/17   
3578              GA    30307                 NaN         NaN   
4066              CA    94015                 NaN      1/2/19   
2504              CA    92673  Tank Garage Winery         NaN   
1577              CA    94107                 NaN    11/27/18   
2276              WA    98032                 NaN         NaN   
1943              CA    94901                 NaN      9/2/18   
4055              WA    98033                 NaN         NaN   

                             Cancel Reason Last Processed Date  ...   age  \
2668                                   NaN              2/4/19  ...  53.0   
2989                       No Reason Given             9/24/18  ...  34.0   
1325  Moved/Difficult to Receive Shipments            11/21/16  ...  26.0   
3578                                   NaN              2/4/19  ...  34.0   
4066                                 Other                 NaN  ...  37.0   
2504                                   NaN              2/4/19  ...  59.0   
1577          Joined Another Winery's Club             9/25/18  ...  45.0   
2276                                   NaN              2/4/19  ...  29.0   
1943                   Switched Club Level              7/9/18  ...  58.0   
4055                                   NaN              2/4/19  ...  44.0   

     isPickup    cancel    signup  clubLength Customer No.  \
2668    False     [nan]   [1, 18]    1.166667        24284   
2989    False  [11, 18]   [4, 18]    0.583333        25807   
1325     True   [4, 17]  [10, 16]    1.500000        17922   
3578    False     [nan]   [9, 18]    1.500000        33146   
4066    False   [1, 19]  [12, 18]    1.083333        35541   
2504     True     [nan]  [11, 17]    2.333333        23495   
1577    False  [11, 18]   [2, 17]    1.750000        19586   
2276    False     [nan]   [9, 17]    2.500000        22718   
1943    False   [9, 18]   [6, 17]    1.250000        21282   
4055    False     [nan]  [12, 18]    1.250000        35484   

      Number Of Transactions  Lifetime Value_y  Last Order Date_y  \
2668                     8.0        $1,281.88              2/4/19   
2989                     3.0          $340.92             9/24/18   
1325                     3.0          $256.57            11/28/16   
3578                     7.0          $686.56              2/4/19   
4066                     2.0           $50.00              1/2/19   
2504                     9.0        $1,232.94              2/4/19   
1577                     8.0        $1,104.03             9/25/18   
2276                    10.0        $1,392.75              2/4/19   
1943                    11.0        $2,133.40             12/3/18   
4055                     4.0          $685.35              2/4/19   

     Last Order Amount  
2668          $173.34   
2989          $157.96   
1325           $15.12   
3578          $176.42   
4066           $50.00   
2504          $154.44   
1577          $157.96   
2276          $178.20   
1943          $307.54   
4055      

In [54]:
path = '../order_history.csv'
data = pd.read_csv(path)

**Aggregate totals by custid**

In [63]:
data["Total"] = data["Quantity"] * data["Price"]
customer_orders = data.groupby("Customer Number").sum()[["Quantity","Total"]]

In [64]:
customer_orders = customer_orders[customer_orders["Total"]!=0]

**Join Quantities and Totals on clubs**

In [66]:
clubs = clubs.merge(customer_orders,how="left",left_on="Customer Number",right_on="Customer Number")

In [69]:
clubs.sample(10)

Club Status Bill Birth Date Ship Birth Date   Ship City Ship State Code  \
1486      Active          1/1/00          1/1/00  Union City              CA   
1267   Cancelled         4/12/76         4/12/76      Novato              CA   
2157      Active         9/11/84         9/11/84    Petaluma              CA   
64        Active          8/7/48          8/7/48     Conyers              GA   
833    Cancelled         8/21/77         8/21/77   niceville              FL   
2450      Active         7/13/87         7/13/87     Chicago              IL   
1616   Cancelled          8/9/72          8/9/72      Moraga              CA   
2173      Active          2/7/91          1/1/90     Houston              TX   
2627      Active        11/28/88        11/28/88   Anchorage              AK   
3184   Cancelled         8/20/73         8/20/73     Wichita              KS   

        Ship Zip     Pickup Location Cancel Date              Cancel Reason  \
1486       94587                 NaN         NaN                        NaN   
1267       94949  Tank Garage Winery      9/8/17  Cutting Expenses/Lost Job   
2157       94952                 NaN         NaN                        NaN   
64         30012                 NaN         NaN                        NaN   
833        32578                 NaN     9/30/16            No Reason Given   
2450       60654                 NaN         NaN                        NaN   
1616       94556                 NaN     1/29/19        Switched Club Level   
2173       77019                 NaN         NaN                        NaN   
2627       99507                 NaN         NaN                        NaN   
3184  67204-1852                 NaN      7/3/18           Testing/Accident   

     Last Processed Date  ...   cancel    signup  clubLength Customer No.  \
1486              2/4/19  ...    [nan]  [12, 16]    3.250000        18993   
1267            11/21/16  ...  [9, 17]   [9, 16]    1.000000        17562   
2157              2/4/19  ...    [nan]   [8, 17]    2.583333        22223   
64                2/4/19  ...    [nan]   [8, 14]    5.583333         7745   
833              9/20/16  ...  [9, 16]   [2, 16]    0.583333        14690   
2450              2/4/19  ...    [nan]  [11, 17]    2.333333        23329   
1616             12/3/18  ...  [1, 19]  [12, 17]    2.083333        19712   
2173              2/4/19  ...    [nan]   [8, 17]    2.583333        22301   
2627              2/4/19  ...    [nan]   [1, 18]    1.166667        24112   
3184                 NaN  ...  [7, 18]   [6, 18]    0.083333        27838   

      Number Of Transactions Lifetime Value_y  Last Order Date_y  \
1486                    14.0       $1,728.42              2/4/19   
1267                     7.0       $1,046.66              9/3/17   
2157                    13.0       $1,379.78             2/17/19   
64                      25.0       $5,072.00              2/4/19   
833                      3.0         $339.66             9/20/16   
2450                    11.0       $1,712.01              2/4/19   
1616                    22.0       $3,584.73              2/4/19   
2173                    11.0       $1,627.01              2/8/19   
2627                     7.0       $1,090.97              2/4/19   
3184                    13.0       $2,374.86             2/19/19   

      Last Order Amount  Quantity    Total  
1486           $172.44        NaN      NaN  
1267           $126.07       38.0  1158.15  
2157            $31.03        NaN      NaN  
64             $173.34       47.0  1855.80  
833            $162.00       12.0   301.50  
2450           $172.13        NaN      NaN  
1616           $143.48        NaN      NaN  
2173            $31.66        NaN      NaN  
2627           $198.50        NaN      NaN  
3184            $86.54        NaN      NaN  

[10 rows x 29 columns]

In [55]:
data.head(10)

OrderNumber  Customer Number   OrderCompletedDate orderstatus ordertype  \
0        48788             1008  2017-09-23 15:42:57   Completed       POS   
1        48788             1008  2017-09-23 15:42:57   Completed       POS   
2        48788             1008  2017-09-23 15:42:57   Completed       POS   
3        48788             1008  2017-09-23 15:42:57   Completed       POS   
4        48788             1008  2017-09-23 15:42:57   Completed       POS   
5        48788             1008  2017-09-23 15:42:57   Completed       POS   
6       104967             5002  2019-03-14 18:43:46   Completed     Promo   
7       104967             5002  2019-03-14 18:43:46   Completed     Promo   
8       104033             5002  2019-03-01 17:53:22   Completed     Promo   
9       103858             5002  2019-02-27 18:35:11   Completed       POS   

   BillCustomerNumber ShipStateCode BillBirthDate ShipZipCode   BillCity  \
0                 NaN            CA           NaN       94515  Calistoga   
1                 NaN            CA           NaN       94515  Calistoga   
2                 NaN            CA           NaN       94515  Calistoga   
3                 NaN            CA           NaN       94515  Calistoga   
4                 NaN            CA           NaN       94515  Calistoga   
5                 NaN            CA           NaN       94515  Calistoga   
6              5002.0            CA    1920-01-01       94515  Calistoga   
7              5002.0            CA    1920-01-01       94515  Calistoga   
8              5002.0            CA    1920-01-01       94515  Calistoga   
9              5002.0            CA    1920-01-01       94515  Calistoga   

  BillZipCode  isPickup  Quantity ProductType           ProductSKU  \
0       94515      True         1        Wine   44.15.750.TK.RB.TE   
1       94515      True         1     Product        CL.HT.3200.BK   
2       94515      True         2        Wine  47.15.750.TK.RB.LYS   
3       94515      True         5     Product                TK.GC   
4       94515      True         2        Wine   44.14.750.TK.CS.RB   
5       94515      True         4     Product              TK.GCIN   
6       94515      True         1        Wine  78.17.750.TK.DFH.RW   
7       94515      True         1        Wine   85.16.750.TK.LN.RW   
8       94515      True         1        Wine   85.16.750.TK.LN.RW   
9       94515      True         1        Wine   85.16.750.TK.LN.RW   

   originalPrice  Price  
0           45.0   31.5  
1           20.0   14.0  
2           50.0   35.0  
3            0.0    0.0  
4           55.0   38.5  
5            0.0    0.0  
6           60.0    0.0  
7           40.0    0.0  
8           40.0    0.0  
9           40.0    0.0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65499 entries, 0 to 65498
Data columns (total 17 columns):
OrderNumber           65499 non-null int64
Customer Number       65499 non-null int64
OrderCompletedDate    65499 non-null object
orderstatus           65499 non-null object
ordertype             65499 non-null object
BillCustomerNumber    64609 non-null float64
ShipStateCode         65356 non-null object
BillBirthDate         44781 non-null object
ShipZipCode           65356 non-null object
BillCity              53068 non-null object
BillZipCode           53267 non-null object
isPickup              65499 non-null bool
Quantity              65499 non-null int64
ProductType           65499 non-null object
ProductSKU            65499 non-null object
originalPrice         65499 non-null float64
Price                 65499 non-null float64
dtypes: bool(1), float64(3), int64(3), object(10)
memory usage: 8.1+ MB


**Cells with NaNs**
```
BillCustomerNumber    64609 non-null float64
ShipStateCode         65356 non-null object
BillBirthDate         44781 non-null object
ShipZipCode           65356 non-null object
BillCity              53068 non-null object
BillZipCode           53267 non-null object
```

In [10]:
( data[data["BillCustomerNumber"].isna()]["Quantity"]*data[data["BillCustomerNumber"].isna()]["Price"] ).sum()

21163.519999999997

In [11]:
( data[~data["BillCustomerNumber"].isna()]["Quantity"]*data[~data["BillCustomerNumber"].isna()]["Price"] ).sum()

2552475.26

In [2]:
import pandas as pd
import numpy as np
from src import eda

In [3]:
data = eda.get_dataframe("data/Order-Data-Sample.csv")

In [4]:
type(data["ShipStateCode"].values[0])

str

In [5]:
data = eda.eliminate_noise_cols(data)

In [6]:
eda.print_stats(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 19 columns):
OrderNumber             24 non-null int64
OrderCompletedDate      24 non-null object
ordertype               24 non-null object
OrderCompletedDate.1    24 non-null object
BillCustomerNumber      22 non-null float64
ShipStateCode           24 non-null object
BillBirthDate           22 non-null object
BillCity                24 non-null object
isPickup                24 non-null bool
ShipCity                24 non-null object
SalesAssociate          24 non-null object
shipmentCount           0 non-null float64
ClubName                0 non-null float64
clubShipmentName        0 non-null float64
Quantity                24 non-null int64
ProductType             24 non-null object
ProductTitle            24 non-null object
originalPrice           24 non-null float64
Price                   24 non-null float64
dtypes: bool(1), float64(6), int64(2), object(10)
memory usage: 3.5+ KB
None
    

In [7]:
data["OrderCompletedDate"][0][:10]

'2019-03-16'

In [8]:
data["CalendarDate"] = np.array([x[:10] for x in data["OrderCompletedDate"]])

In [9]:
data = data.drop(columns=["OrderCompletedDate","OrderCompletedDate.1"])

In [10]:
data.head()

OrderNumber ordertype  BillCustomerNumber ShipStateCode BillBirthDate  \
0       105207     Promo              5006.0            CA    1920-01-01   
1       105206     Promo             28868.0            CA    1984-07-13   
2       105204     Promo              5008.0            CA    1920-01-01   
3       105204     Promo              5008.0            CA    1920-01-01   
4       105204     Promo              5008.0            CA    1920-01-01   

    BillCity  isPickup   ShipCity SalesAssociate  shipmentCount  ClubName  \
0  Calistoga      True  Calistoga          Promo            NaN       NaN   
1   Bensalem      True  Calistoga          Promo            NaN       NaN   
2  Calistoga      True  Calistoga          Promo            NaN       NaN   
3  Calistoga      True  Calistoga          Promo            NaN       NaN   
4  Calistoga      True  Calistoga          Promo            NaN       NaN   

   clubShipmentName  Quantity ProductType  \
0               NaN         4        Wine   
1               NaN         1     Product   
2               NaN         6        Wine   
3               NaN         3        Wine   
4               NaN         1        Wine   

                                        ProductTitle  originalPrice  Price  \
0             2018 Stars Like Ours, Rosé, California           22.0    0.0   
1               Lords of the Boulevard T-Shirt White           30.0    0.0   
2           2017 Petty Cash, White Wine, Napa Valley           35.0    0.0   
3  2017 HUF Downhill from Here, Red Wine, California           60.0    0.0   
4              2017 Airwaves, White Wine, California           32.0    0.0   

  CalendarDate  
0   2019-03-16  
1   2019-03-16  
2   2019-03-16  
3   2019-03-16  
4   2019-03-16

**This aggregates revenue at the customer level:**

In [11]:
data["Total"] = data["Quantity"] * data["Price"]
revenue_by_user = data.groupby("BillCustomerNumber").sum()["Total"]

In [12]:
revenue_by_user

BillCustomerNumber
5006.0      0.00
5008.0      0.00
28868.0    80.75
38198.0     0.00
Name: Total, dtype: float64

In [13]:
data.sample(5)

OrderNumber ordertype  BillCustomerNumber ShipStateCode BillBirthDate  \
2        105204     Promo              5008.0            CA    1920-01-01   
10       105203       POS             28868.0            CA    1984-07-13   
20       105200       POS                 NaN            CA           NaN   
17       105201     Promo              5008.0            CA    1920-01-01   
8        105204     Promo              5008.0            CA    1920-01-01   

     BillCity  isPickup   ShipCity   SalesAssociate  shipmentCount  ClubName  \
2   Calistoga      True  Calistoga            Promo            NaN       NaN   
10   Bensalem      True  Calistoga   Mario Gallardo            NaN       NaN   
20  Calistoga      True  Calistoga  Austin Giuliano            NaN       NaN   
17  Calistoga      True  Calistoga            Promo            NaN       NaN   
8   Calistoga      True  Calistoga            Promo            NaN       NaN   

    clubShipmentName  Quantity ProductType  \
2                NaN         6        Wine   
10               NaN         1     Product   
20               NaN         3     Product   
17               NaN         4        Wine   
8                NaN         1        Wine   

                                         ProductTitle  originalPrice  Price  \
2            2017 Petty Cash, White Wine, Napa Valley           35.0    0.0   
10                             Tank Logo T-Shirt Gray           30.0   25.5   
20                                            Tasting           23.2   23.2   
17             2018 Stars Like Ours, Rosé, California           22.0    0.0   
8   2017 Young, Wild & Free, Zinfandel, Dry Creek ...           45.0    0.0   

   CalendarDate  Total  
2    2019-03-16    0.0  
10   2019-03-16   25.5  
20   2019-03-16   69.6  
17   2019-03-16    0.0  
8    2019-03-16    0.0

In [31]:
conditions = (data["ordertype"]=="Promo") & (data["ProductType"]=="Wine")
cogs = data[conditions]
total_bottles_poured = cogs.groupby("CalendarDate").sum()["Quantity"]

In [30]:
total_bottles

CalendarDate
2019-03-16    69
Name: Quantity, dtype: int64